import { pathToFileURL } from "node:url";
import { mkdir } from "node:fs/promises";
import assert from "node:assert/strict";
const { chromium } = await import(pathToFileURL(process.argv[2]).href);
const browser = await chromium.launch({ channel: "msedge", headless: true });
const page = await browser.newPage({ viewport: { width: 1490, height: 1054 } });
const errors = [];
page.on("pageerror", error => errors.push(error.message));
await mkdir(".courio-review", { recursive: true });
try {
  await page.goto("http://127.0.0.1:5173");
  await page.locator('[data-login-account="admin-owner"]').click();
  await page.locator(".auth-overlay").waitFor({ state: "hidden" });
  await page.locator('[data-destination="tasks"]').click();
  await page.locator('[data-add-task]').click();
  await page.locator('[data-task-editor] [name="title"]').fill("Manual QA task");
  await page.locator('[data-task-editor] [name="notes"]').fill("Original note");
  await page.locator('[data-task-editor] [name="dueAt"]').fill("2026-10-02");
  await page.locator('[data-task-editor] [name="assignedTo"]').selectOption("emp-2");
  await page.locator('[data-task-editor] button[type="submit"]').click();
  await page.locator('[data-task-editor]').waitFor({ state: "hidden" });
  await page.locator('#tasks .queue-item').filter({ hasText: "Manual QA task" }).click();
  await page.locator('[data-edit-task]').click();
  await page.locator('[data-task-editor] [name="notes"]').fill("Changed note");
  await page.locator('[data-task-editor] button[type="submit"]').click();
  await page.locator('[data-task-editor]').waitFor({ state: "hidden" });
  await page.locator('[data-review-task]').click();
  await page.locator('[data-restore-task]').last().click();
  await page.locator('[data-confirm-cancel]').click();
  await page.locator('[data-restore-task]').last().click();
  await page.locator('[data-confirm-primary]').click();
  await page.waitForFunction(() => document.querySelector('.task-history-list')?.textContent.includes('Task change restored'));
  await page.locator('.review-drawer [data-close-drawer]').last().click();
  assert.equal(await page.locator('[data-task-note]').inputValue(), "Original note");
  await page.reload();
  await page.locator('[data-destination="tasks"]').click();
  await page.locator('#tasks .queue-item').filter({ hasText: "Manual QA task" }).click();
  assert.equal(await page.locator('[data-task-note]').inputValue(), "Original note");
  await page.locator('[data-task-assignee-filter]').selectOption("emp-2");
  assert.equal(await page.locator('#tasks .queue-workspace').count(), 1);
  await page.locator('[data-destination="triage"]').click();
  await page.locator('#triage .queue-item').first().click();
  await page.locator('[data-email-task]').click();
  await page.locator('[data-task-editor] [name="assignedTo"]').selectOption("emp-2");
  await page.locator('[data-task-editor] button[type="submit"]').click();
  await page.locator('[data-task-editor]').waitFor({ state: "hidden" });
  await page.screenshot({ path: '.courio-review/tasks-new-desktop.png' });
  await page.locator('[data-destination="admin"]').last().click();
  await page.locator('[data-setting="language"]').selectOption("fr");
  await page.locator('[data-save-settings]').click();
  await page.locator('[data-save-settings]:enabled').waitFor();
  await page.locator('[data-destination="tasks"]').click();
  await page.locator('[data-add-task]').click();
  assert.equal(await page.locator('[data-task-editor] button[type="submit"]').innerText(), "Enregistrer la tâche");
  await page.screenshot({ path: '.courio-review/task-editor-fr.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: '.courio-review/task-editor-mobile.png' });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.locator('.review-drawer [data-close-drawer]').click();
  await page.setViewportSize({ width: 1490, height: 1054 });
  await page.locator('[data-logout-demo]').click();
  await page.locator('[data-login-account="employee-marcus"]').click();
  await page.locator('.auth-overlay').waitFor({ state: 'hidden' });
  await page.locator('#tasks .queue-item').filter({ hasText: 'Manual QA task' }).click();
  assert.equal(await page.locator('[data-task-note]').inputValue(), 'Original note');
  await page.locator('[data-edit-task]').click();
  assert.equal(await page.locator('[data-task-editor] [name="assignedTo"]').count(), 0);
  await page.locator('.review-drawer [data-close-drawer]').click();
  await page.locator('[data-add-task]').click();
  await page.locator('[data-task-editor] [name="title"]').fill('Employee personal task');
  await page.locator('[data-task-editor] button[type="submit"]').click();
  await page.locator('[data-task-editor]').waitFor({ state: 'hidden' });
  assert.equal(await page.locator('#tasks .queue-item').filter({ hasText: 'Employee personal task' }).count(), 1);
  assert.deepEqual(errors, []);
  console.log('PASS: task create/edit/restore/cancel, persistence, filters, email delegation editor, French, mobile overflow.');
} finally { await browser.close(); }
